### PR TITLE
Conditional test case

### PR DESCRIPTION
**Pull request by FabrizioMoggio**
- test case for the conditional endpoint and unconditional endpoint with phone number from access token.
- a very minor update on the unconditional .feature file

#### What type of PR is this?
* documentation

#### What this PR does / why we need it:
to be compliant with commonalities

#### Which issue(s) this PR fixes:
https://github.com/camaraproject/CallForwardingSignal/discussions/35#discussioncomment-9996837
https://github.com/camaraproject/CallForwardingSignal/issues/51
compatible with: https://github.com/camaraproject/CallForwardingSignal/pull/48

### CODE REVIEW

**Comment by bigludo7** [comment]
Hello Fabrizio,

Few comments ... most of them my fault as came from the first test definition PR.

- We should add a Test Case for 403 `PERMISSION_DENIED` as it is defined in the yaml but not test case. --> my proposal: we can do it in this PR

- We have test cases for 409, 415 & 429 but these errors are not defined in the yaml - either we add them in the yaml or we remove the tests --> my proposal:  Add these errors in our yaml are defined in [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml#L269)  - this should be another PR for the yamls.

- I've doubt about keeping 503 & 504 error. It means that as implementer you have to shutdown your implem for testing --> my proposal: I'm in favor to remove them in the test definition

**Comment by FabrizioMoggio** [comment]
> Hello Fabrizio,
> 
> Few comments ... most of them my fault as came from the first test definition PR.
> 
> * We should add a Test Case for 403 `PERMISSION_DENIED` as it is defined in the yaml but not test case. --> my proposal: we can do it in this PR
> * We have test cases for 409, 415 & 429 but these errors are not defined in the yaml - either we add them in the yaml or we remove the tests --> my proposal:  Add these errors in our yaml are defined in [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml#L269)  - this should be another PR for the yamls.
> * I've doubt about keeping 503 & 504 error. It means that as implementer you have to shutdown your implem for testing --> my proposal: I'm in favor to remove them in the test definition

About 403, you are right. I'm going to add it.

409, 415, 429 are in the current PR rel 0.2.0, that we should approve today :-) (hopefully)

503, 504 I had the same doubt, ok to remove them.

**Comment by FabrizioMoggio** [comment]
please consider: https://github.com/camaraproject/Commonalities/discussions/248

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
