### PR TITLE
OpenId aligment with SimSwap

### PR DESCRIPTION
**Pull request by FabrizioMoggio**
#### What type of PR is this?

* correction

#### What this PR does / why we need it:
alignment with SimSwap -> openId:api-name:method-name

paths:
  /retrieve-date:
    post:
      security:
        - openId:
          - sim-swap:retrieve-date

### CODE REVIEW

**Comment by FabrizioMoggio** [comment]
@bigludo7 I honestly don't know if this is correct :-). MegaLinter on the TI API gave me some problem on the openId section which I copied from CFS. To solve it I looked at SimSwap and I noticed a different formatting for openId. What do you think? In addition to the formatting changes, do we also need ":read or :write"?

**Comment by bigludo7** [comment]
Hello @FabrizioMoggio 
i tend to think that we need to have as scope value `call-forwarding-signal:call-forwarding:read` indeed with call-forwarding-signal:call-forwarding we can think that this scope allow you to trigger the call forwarding fonction itself. WDYT?

**Comment by FabrizioMoggio** [comment]
@bigludo7 please can you have a look on the openId definition? I run MegaLinter on the YAML and I got:

Error: 99:11 [indentation] wrong indentation: expected 12 but found 10

I can't understand where the problem is.

**Comment by FabrizioMoggio** [comment]
the problem is in the double indentation apparently but I can't understand why it is considered wrong

**Comment by FabrizioMoggio** [comment]
dear @rartych thank you very much. the indentation was correct. what was missing was:

      security:
        - openId:
            - 'call-forwarding-signal:call-forwardings:read'

I used prettify-yaml as you suggested. :-)

**Review by bigludo7 — DISMISSED** [review]
LGTM

**Comment by FabrizioMoggio** [comment]
The Carriage Return coding is still in Windows format rather than in Linux.  I will fix this with a new PR, when this YAML is approved and merged. this because otherwise you can not see the differences because that modification affects all the code lines.

**Pull request merged**
