### PR TITLE
Create README2.md

### PR DESCRIPTION
**Pull request by FabrizioMoggio**
link to Confluence for the meeting minutes

#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

To provide a link to the CFS Confluence wiki Page where the Meeting minutes are stored.

### CODE REVIEW

**Comment by FabrizioMoggio** [comment]
I couldn't edit the original README.md, for this reason a created a new one. After this file will be approved, I will delete the original README.md and rename README2.md into README.md

**Review by bigludo7 — COMMENTED** [review]
Fixed the sentence with Call Forwarding signal and not QoD ;)

**Review by FabrizioMoggio — COMMENTED** [review]
I don't get it. In my repository it is already:

Starting with the beginning of 2024 the meeting minutes of **Call Forwarding Signal**

I also checked the PR and I don't see Quality on Demand, that was actually the "template" I started from.

**Comment by FabrizioMoggio** [comment]
now I get it? @bigludo7 you did the changes. thank you.

**Review by FabrizioMoggio — COMMENTED** [review]
Correct

**Comment by FabrizioMoggio** [comment]
@bigludo7 I think you need to approve to move forward.

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
